name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_REGISTRY: ${{ vars.ACR_REGISTRY }}
  ACR_NAMESPACE: ${{ vars.ACR_NAMESPACE }}
  IMAGE_NAME: ${{ vars.ACR_IMAGE_NAME || 'ai-travel-planner' }}

jobs:
  build-and-push:
    if: ${{ env.ACR_REGISTRY != '' && env.ACR_NAMESPACE != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Alibaba Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ACR_REGISTRY }}/${{ env.ACR_NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  missing-config:
    if: ${{ env.ACR_REGISTRY == '' || env.ACR_NAMESPACE == '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail workflow if registry variables are missing
        run: |
          echo "Repository variables ACR_REGISTRY and ACR_NAMESPACE must be set for this workflow to run."
          exit 1
